import { supabase } from '../supabaseClient';
import { Item, Aluguel, ItemAlugado } from '../types';

export const dataService = {
  // Get all items
  getItems: async (): Promise<Item[]> => {
    const { data, error } = await supabase
      .from('items')
      .select('*')
      .order('nome');

    if (error) throw error;
    return data || [];
  },

  // Get all rentals
  getRentals: async (): Promise<Aluguel[]> => {
    const { data, error } = await supabase
      .from('rentals')
      .select('*')
      .order('data_entrega', { ascending: false });

    if (error) throw error;
    return data || [];
  },

  // Get rented items for a specific rental
  getRentedItems: async (rentalId: string): Promise<ItemAlugado[]> => {
    const { data, error } = await supabase
      .from('rented_items')
      .select('*')
      .eq('aluguel_id', rentalId);

    if (error) throw error;
    return data || [];
  },

  // Save a new rental
  saveRental: async (rental: Aluguel, newItems: { item: Item, qty: number }[]): Promise<void> => {
    // 1. Validate Stock (Client-side check before server attempts)
    // Fetch latest stock to be safe
    const latestItems = await dataService.getItems();
    newItems.forEach(({ item, qty }) => {
        const storedItem = latestItems.find(i => i.id === item.id);
        if (storedItem) {
            if (storedItem.estoque_limpo < qty) {
                throw new Error(`Estoque insuficiente para: ${storedItem.nome}`);
            }
        }
    });

    // 2. Create Rental
    // Remove 'id' if it's auto-generated or allow it if UUID provided.
    // The interface has 'id', usually generated by DB.
    // We'll omit 'id' so Supabase generates it, then we get it back.
    const { id, ...rentalData } = rental;

    const { data: rentalResult, error: rentalError } = await supabase
        .from('rentals')
        .insert([rentalData])
        .select()
        .single();

    if (rentalError) throw rentalError;
    const newRentalId = rentalResult.id;

    // 3. Create Rented Items
    const rentedItemsData = newItems.map(({ item, qty }) => ({
        aluguel_id: newRentalId,
        item_id: item.id,
        quantidade: qty
    }));

    const { error: itemsError } = await supabase
        .from('rented_items')
        .insert(rentedItemsData);

    if (itemsError) {
        // Rollback rental? For simplicity, we just throw.
        // Ideally we would delete the rental.
        await supabase.from('rentals').delete().eq('id', newRentalId);
        throw itemsError;
    }

    // 4. Update Stock
    // We do this sequentially or parallel. RPC is better but client-side loop is acceptable for prototype.
    for (const { item, qty } of newItems) {
        const { error: stockError } = await supabase.rpc('decrement_stock', {
            row_id: item.id,
            quantity: qty
        });

        // Fallback if RPC doesn't exist (user needs to create it, or we do direct update)
        if (stockError) {
             // Fallback: Read-Modify-Write (Optimistic)
             // We already checked stock at step 1.
             await supabase
                .from('items')
                .update({ estoque_limpo: item.estoque_limpo - qty })
                .eq('id', item.id);
        }
    }
  },

  // Cancel a rental
  cancelRental: async (rentalId: string): Promise<void> => {
    // Get rented items to know what to restore
    const rentedItems = await dataService.getRentedItems(rentalId);

    // Update Status
    const { error: statusError } = await supabase
        .from('rentals')
        .update({ status: 'Cancelado' })
        .eq('id', rentalId);

    if (statusError) throw statusError;

    // Restore Stock
    for (const ri of rentedItems) {
        // We need to fetch current item state to increment
        const { data: item } = await supabase.from('items').select('estoque_limpo').eq('id', ri.item_id).single();
        if (item) {
             await supabase
            .from('items')
            .update({ estoque_limpo: item.estoque_limpo + ri.quantidade })
            .eq('id', ri.item_id);
        }
    }
  },

  // Check-in a rental
  checkInRental: async (rentalId: string, returns: { itemId: string, limpo: number, sujo: number, quebrado: number }[]): Promise<void> => {
    // Update Status
    const { error: statusError } = await supabase
        .from('rentals')
        .update({ status: 'Concluído' })
        .eq('id', rentalId);

    if (statusError) throw statusError;

    // Update Stock
    for (const ret of returns) {
        const { data: item } = await supabase.from('items').select('*').eq('id', ret.itemId).single();
        if (item) {
            await supabase.from('items').update({
                estoque_limpo: item.estoque_limpo + ret.limpo,
                estoque_sujo: item.estoque_sujo + ret.sujo,
                estoque_manutencao: item.estoque_manutencao + ret.quebrado
            }).eq('id', ret.itemId);
        }
    }
  },

  // Clean items
  cleanItem: async (itemId: string, qty: number): Promise<void> => {
    const { data: item } = await supabase.from('items').select('*').eq('id', itemId).single();

    if (!item) throw new Error('Item not found');
    if (item.estoque_sujo < qty) throw new Error('Quantity exceeds dirty stock');

    const { error } = await supabase.from('items').update({
        estoque_sujo: item.estoque_sujo - qty,
        estoque_limpo: item.estoque_limpo + qty
    }).eq('id', itemId);

    if (error) throw error;
  }
};
